name: Fly Deploy
on:
  push:
    branches:
      - main # ដំណើរការពេល push ចូល branch main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # ការពារកុំឱ្យ Deploy ជាន់គ្នា
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
